version: '3'
services:
    oxio-golang-protoc-version:
        image: oxio/golang-protoc:1.2
        container_name: oxio/golang-protoc
        build:
            context: .
            args:
                - protobuf_version=3.5.1
    oxio-golang-protoc-latest:
        image: oxio/golang-protoc:latest
        container_name: oxio/golang-protoc
        build:
            context: .
            args:
                - protobuf_version=3.5.1
